name: hello-world

on: push

jobs:

  gated-checkin:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v3
      - name: Review Seed file change
        working-directory: ./automation/codereviews
        shell: pwsh
        env:
          baseCommitSha: ${{ github.base_ref }}
          changeCommitSha: ${{ github.sha }}
        run: |
          .\seedfile.ps1 -BaseCommitSha $env:baseCommitSha -ChangeCommitSha $env:changeCommitSha