name: hello-world

on: push

jobs:
  check-seed-file:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        working-directory: automation/codereviews
        shell: pwsh
        run: |
          ./seedfile.ps1