name: hello-world

on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json headRefOid -q .headRefOid || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.pr.outputs.pull_request_number }}

  pull-request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo ${{ github.event.number }}

  gated-checkin:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - uses: actions/checkout@v3
      - name: Review Seed file change
        working-directory: ./automation/codereviews
        shell: pwsh
        env:
          baseCommitSha: ${{ toJSON(github) }}
          changeCommitSha: ${{ github.sha }}
          GH_TOKEN: ${{ github.token }}
        run: |
          .\seedfile.ps1 -BaseCommitSha $env:baseCommitSha -ChangeCommitSha $env:changeCommitSha